export function someFunction() {
  console.log('someFunction')
}

export class SomeClass {
  print() {
    console.log('hello there')
  }
}

export class UnusedBigClass {
  print() {
    console.log('UnusedBigClass')

    console.log(`
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Non consectetur a erat nam at lectus. Dolor sit amet consectetur adipiscing elit ut aliquam purus sit. Tristique magna sit amet purus gravida. Semper feugiat nibh sed pulvinar. Tincidunt vitae semper quis lectus nulla at. Ut tortor pretium viverra suspendisse potenti nullam ac. Tempor orci dapibus ultrices in. Vestibulum sed arcu non odio euismod lacinia at quis risus. Nascetur ridiculus mus mauris vitae ultricies. Magna eget est lorem ipsum dolor sit. Tempor orci dapibus ultrices in iaculis nunc sed.

    Euismod elementum nisi quis eleifend. Amet facilisis magna etiam tempor orci eu. Cras semper auctor neque vitae. Sit amet justo donec enim diam vulputate ut pharetra. In est ante in nibh mauris cursus mattis. Ultricies lacus sed turpis tincidunt id aliquet. Id faucibus nisl tincidunt eget nullam non nisi. Eget duis at tellus at urna condimentum mattis. Et malesuada fames ac turpis egestas integer eget aliquet. Sed vulputate mi sit amet mauris commodo quis. Vitae justo eget magna fermentum iaculis eu non. Venenatis a condimentum vitae sapien.
    
    A condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Porta lorem mollis aliquam ut porttitor leo a diam sollicitudin. Tempor nec feugiat nisl pretium fusce id velit ut. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi tristique. Feugiat in ante metus dictum at tempor. Eget est lorem ipsum dolor sit amet consectetur adipiscing elit. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Consectetur libero id faucibus nisl tincidunt. At risus viverra adipiscing at in tellus integer feugiat. Dignissim suspendisse in est ante in nibh mauris.
    
    Adipiscing diam donec adipiscing tristique risus nec feugiat in. In cursus turpis massa tincidunt dui ut ornare lectus. Cursus euismod quis viverra nibh cras pulvinar. Dui nunc mattis enim ut tellus elementum. Massa tincidunt nunc pulvinar sapien. Malesuada bibendum arcu vitae elementum curabitur vitae. Fringilla ut morbi tincidunt augue interdum velit euismod in pellentesque. Non odio euismod lacinia at. Ut sem nulla pharetra diam sit amet nisl. Dolor purus non enim praesent. Sagittis vitae et leo duis ut diam quam. Et sollicitudin ac orci phasellus egestas tellus rutrum. Sit amet mauris commodo quis. Consectetur adipiscing elit ut aliquam purus sit. Blandit turpis cursus in hac habitasse platea dictumst. Lectus urna duis convallis convallis tellus id interdum. Neque volutpat ac tincidunt vitae semper quis lectus nulla. Nisl condimentum id venenatis a. Aliquam vestibulum morbi blandit cursus risus. Malesuada fames ac turpis egestas maecenas pharetra convallis.
    
    Eu facilisis sed odio morbi quis commodo odio aenean. Blandit aliquam etiam erat velit scelerisque. Diam ut venenatis tellus in. Eu tincidunt tortor aliquam nulla. Quam quisque id diam vel quam elementum. Hac habitasse platea dictumst quisque sagittis purus sit amet. Sit amet facilisis magna etiam tempor orci eu. Luctus accumsan tortor posuere ac ut consequat semper viverra. Lacus vel facilisis volutpat est velit egestas dui. Nunc congue nisi vitae suscipit tellus. Purus sit amet luctus venenatis lectus magna. Tellus integer feugiat scelerisque varius. Eget nunc scelerisque viverra mauris in aliquam sem fringilla ut. Neque sodales ut etiam sit amet nisl purus in. Neque convallis a cras semper auctor neque vitae tempus quam. Vulputate sapien nec sagittis aliquam. Faucibus turpis in eu mi bibendum neque egestas. Rhoncus dolor purus non enim praesent elementum.
    
    Neque viverra justo nec ultrices dui sapien eget. Nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit. Aenean sed adipiscing diam donec adipiscing tristique. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Viverra maecenas accumsan lacus vel. Imperdiet sed euismod nisi porta lorem mollis aliquam ut. Sit amet luctus venenatis lectus magna fringilla urna porttitor. A arcu cursus vitae congue mauris. Tellus molestie nunc non blandit massa enim nec dui. Vitae aliquet nec ullamcorper sit amet risus nullam. Aliquet lectus proin nibh nisl condimentum id venenatis a condimentum. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Mi eget mauris pharetra et ultrices neque ornare aenean. Id volutpat lacus laoreet non curabitur gravida arcu. Eget nulla facilisi etiam dignissim diam quis enim. Id eu nisl nunc mi ipsum faucibus vitae aliquet.
    
    Amet consectetur adipiscing elit ut aliquam. Nunc sed id semper risus in. Blandit aliquam etiam erat velit scelerisque in dictum non consectetur. Est lorem ipsum dolor sit amet consectetur adipiscing. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. At tellus at urna condimentum mattis pellentesque id. Aliquam nulla facilisi cras fermentum odio. Id velit ut tortor pretium viverra suspendisse potenti. Dis parturient montes nascetur ridiculus. Nisi est sit amet facilisis magna etiam tempor. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt. Eget mi proin sed libero enim sed faucibus turpis in. Neque gravida in fermentum et sollicitudin ac. Sem viverra aliquet eget sit amet tellus cras adipiscing. Ultricies integer quis auctor elit sed vulputate mi sit amet. Penatibus et magnis dis parturient montes.
    
    Id eu nisl nunc mi ipsum faucibus. Duis at consectetur lorem donec massa. Aliquet bibendum enim facilisis gravida neque convallis a cras. Urna molestie at elementum eu. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Ac feugiat sed lectus vestibulum mattis ullamcorper. Et leo duis ut diam quam nulla porttitor massa. Tempus egestas sed sed risus. Augue lacus viverra vitae congue. Est ante in nibh mauris cursus mattis molestie a. Nulla pharetra diam sit amet nisl. Neque volutpat ac tincidunt vitae semper quis lectus nulla. Quis viverra nibh cras pulvinar mattis nunc sed blandit libero. Consequat semper viverra nam libero justo laoreet. Pellentesque nec nam aliquam sem et tortor consequat. Feugiat in ante metus dictum at. Vitae justo eget magna fermentum. Eget nulla facilisi etiam dignissim diam. Ultricies tristique nulla aliquet enim tortor at auctor urna nunc.
    
    In est ante in nibh mauris. Quis commodo odio aenean sed adipiscing diam. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Turpis nunc eget lorem dolor sed viverra ipsum nunc aliquet. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Nunc sed blandit libero volutpat sed cras. Amet consectetur adipiscing elit ut aliquam purus sit amet luctus. Amet commodo nulla facilisi nullam vehicula ipsum a arcu. Urna neque viverra justo nec ultrices dui sapien eget mi. Arcu ac tortor dignissim convallis aenean et tortor at. Pharetra vel turpis nunc eget lorem. Non quam lacus suspendisse faucibus. Vulputate sapien nec sagittis aliquam malesuada. Pulvinar etiam non quam lacus suspendisse. Porttitor eget dolor morbi non arcu risus quis. Mauris in aliquam sem fringilla ut morbi tincidunt. Vel risus commodo viverra maecenas accumsan. Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a. Quis vel eros donec ac odio tempor orci dapibus ultrices.
    
    Convallis tellus id interdum velit laoreet id donec ultrices. Quis vel eros donec ac odio tempor orci dapibus ultrices. Diam phasellus vestibulum lorem sed risus ultricies. Ultricies mi eget mauris pharetra et ultrices neque. Sollicitudin ac orci phasellus egestas tellus rutrum. Lorem mollis aliquam ut porttitor leo. Congue nisi vitae suscipit tellus mauris a diam maecenas. Vitae tortor condimentum lacinia quis vel eros donec ac odio. Diam vel quam elementum pulvinar etiam non quam. Duis tristique sollicitudin nibh sit amet commodo nulla. Vulputate ut pharetra sit amet aliquam id diam maecenas ultricies. Pharetra pharetra massa massa ultricies mi. Orci a scelerisque purus semper. Risus ultricies tristique nulla aliquet enim tortor. Libero id faucibus nisl tincidunt eget. Cras pulvinar mattis nunc sed blandit libero volutpat sed cras.
`)
  }
}